# Generated by Django 3.2.5 on 2021-09-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='country',
            field=models.CharField(default='India', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='sport',
            field=models.CharField(default='Cricket', max_length=32),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
