# Generated by Django 3.2.5 on 2021-09-02 07:11

import basic_app.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0003_auto_20210901_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='country',
            field=models.CharField(max_length=32,),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='sport',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=32,),
        ),
        migrations.CreateModel(
            name='Result_Men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=32,)),
                ('bronze_medal', models.ForeignKey(blank='False', on_delete=django.db.models.deletion.CASCADE, related_name='bronze', to=settings.AUTH_USER_MODEL)),
                ('gold_medal', models.ForeignKey(blank='False', on_delete=django.db.models.deletion.CASCADE, related_name='gold', to=settings.AUTH_USER_MODEL)),
                ('silver_medal', models.ForeignKey(blank='False', on_delete=django.db.models.deletion.CASCADE, related_name='silver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
