# Generated by Django 3.2.5 on 2021-09-02 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0007_alter_result_men_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result_men',
            name='bronze_medal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bronze', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='result_men',
            name='gold_medal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='result_men',
            name='silver_medal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silver', to=settings.AUTH_USER_MODEL),
        ),
    ]
