# Generated by Django 3.2.5 on 2021-09-02 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0010_auto_20210902_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result_men',
            name='bronze_medal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze_men', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='result_men',
            name='gold_medal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_men', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='result_men',
            name='silver_medal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silver_men', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Result_Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='', max_length=32)),
                ('bronze_medal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze_women', to=settings.AUTH_USER_MODEL)),
                ('gold_medal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_women', to=settings.AUTH_USER_MODEL)),
                ('silver_medal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silver_women', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
