# Generated by Django 3.2.5 on 2021-09-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_auto_20210902_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result_men',
            name='sport',
            field=models.CharField(choices=[('Cr', 'Cricket'), ('Fb', 'Football'), ('Ho', 'Hockey'), ('Bm', '/Badminton'), ('Vb', 'Volleyball')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='sport',
            field=models.CharField(choices=[('Cr', 'Cricket'), ('Fb', 'Football'), ('Ho', 'Hockey'), ('Bm', '/Badminton'), ('Vb', 'Volleyball')], max_length=32),
        ),
    ]
