# Generated by Django 3.2.5 on 2021-09-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_auto_20210902_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result_men',
            name='sport',
            field=models.CharField(choices=[('Cr', 'Cricket'), ('Fb', 'Football'), ('Ho', 'Hockey'), ('Bm', 'Badminton'), ('Vb', 'Volleyball')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='result_women',
            name='sport',
            field=models.CharField(choices=[('Cr', 'Cricket'), ('Fb', 'Football'), ('Ho', 'Hockey'), ('Bm', 'Badminton'), ('Vb', 'Volleyball')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='sport',
            field=models.CharField(choices=[('Cr', 'Cricket'), ('Fb', 'Football'), ('Ho', 'Hockey'), ('Bm', 'Badminton'), ('Vb', 'Volleyball')], max_length=32),
        ),
    ]
