# Generated by Django 3.2.5 on 2021-09-02 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0013_auto_20210902_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='country',
            field=models.CharField(choices=[('Ind', 'India'), ('Jpn', 'Japan'), ('Chn', 'China'), ('Usa', 'Usa'), ('Rs', 'Russia')], max_length=32),
        ),
        migrations.CreateModel(
            name='Medals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Ind', 'India'), ('Jpn', 'Japan'), ('Chn', 'China'), ('Usa', 'Usa'), ('Rs', 'Russia')], max_length=32)),
                ('bronze_medal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze_country', to=settings.AUTH_USER_MODEL)),
                ('gold_medal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_country', to=settings.AUTH_USER_MODEL)),
                ('silver_medal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silver_country', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
