# Generated by Django 3.2.5 on 2021-09-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_alter_medals_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medals',
            name='country',
            field=models.CharField(choices=[('Ind', 'India'), ('Jpn', 'Japan'), ('Chn', 'China'), ('Usa', 'Usa'), ('Rs', 'Russia')], default='', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='result_men',
            name='sport',
            field=models.CharField(choices=[('Cr', 'Cricket'), ('Fb', 'Football'), ('Ho', 'Hockey'), ('Bm', 'Badminton'), ('Vb', 'Volleyball')], default='', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='result_women',
            name='sport',
            field=models.CharField(choices=[('Cr', 'Cricket'), ('Fb', 'Football'), ('Ho', 'Hockey'), ('Bm', 'Badminton'), ('Vb', 'Volleyball')], default='', max_length=32, unique=True),
        ),
    ]
