# Generated by Django 3.2.5 on 2021-09-02 10:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0018_auto_20210902_1544'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='result_women',
            name='Unique_winner',
        ),
        migrations.AlterUniqueTogether(
            name='result_men',
            unique_together={('gold_medal', 'silver_medal', 'bronze_medal')},
        ),
        migrations.AlterUniqueTogether(
            name='result_women',
            unique_together={('gold_medal', 'silver_medal', 'bronze_medal')},
        ),
    ]
