# Generated by Django 3.2.5 on 2021-09-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0020_auto_20210902_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medals',
            old_name='total_meadals',
            new_name='total_medals',
        ),
    ]
