# Generated by Django 3.2.5 on 2021-09-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0022_alter_medals_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medals',
            options={'ordering': ['gold_medal', 'silver_medal', 'bronze_medal', 'total_medals']},
        ),
    ]
