# Generated by Django 3.2.5 on 2021-10-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0024_auto_20211001_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medals',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('Japan', 'Japan'), ('China', 'China'), ('Usa', 'Usa'), ('Russia', 'Russia')], default='', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='result_women',
            name='sport',
            field=models.CharField(choices=[('Cricket', 'Cricket'), ('Football', 'Football'), ('Hockey', 'Hockey'), ('Badminton', 'Badminton'), ('Volleyball', 'Volleyball')], default='', max_length=32, unique=True),
        ),
    ]
