# Generated by Django 3.2.5 on 2021-10-02 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0025_auto_20211001_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_number', models.IntegerField()),
                ('Category', models.CharField(choices=[('Ac', 'Ac'), ('Non_Ac', 'Non-Ac')], max_length=10)),
                ('Capacity', models.IntegerField()),
                ('Beds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('Athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.room')),
            ],
        ),
    ]
